"""initial migration with floors_total

Revision ID: 2ff3b75c58c8
Revises: 
Create Date: 2026-02-13 11:23:26.319602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff3b75c58c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=5), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floors_total', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flat_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flat_title'))

    op.drop_table('flat')
    # ### end Alembic commands ###
